# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Records.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Records(object):
    def setupUi(self, Records):
        Records.setObjectName("Records")
        Records.resize(750, 601)
        self.centralwidget = QtWidgets.QWidget(Records)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 731, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 14, 151, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Performance_Combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Performance_Combo.setObjectName("Performance_Combo")
        self.verticalLayout.addWidget(self.Performance_Combo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Customer_Combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Customer_Combo.setObjectName("Customer_Combo")
        self.verticalLayout.addWidget(self.Customer_Combo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.SeatID_Combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.SeatID_Combo.setObjectName("SeatID_Combo")
        self.verticalLayout.addWidget(self.SeatID_Combo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.CustType_Combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CustType_Combo.setObjectName("CustType_Combo")
        self.verticalLayout.addWidget(self.CustType_Combo)
        self.RecordsTable = QtWidgets.QTableWidget(self.frame)
        self.RecordsTable.setGeometry(QtCore.QRect(170, 10, 551, 511))
        self.RecordsTable.setObjectName("RecordsTable")
        self.RecordsTable.setColumnCount(0)
        self.RecordsTable.setRowCount(0)
        Records.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Records)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 26))
        self.menubar.setObjectName("menubar")
        Records.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Records)
        self.statusbar.setObjectName("statusbar")
        Records.setStatusBar(self.statusbar)

        self.retranslateUi(Records)
        QtCore.QMetaObject.connectSlotsByName(Records)

    def retranslateUi(self, Records):
        _translate = QtCore.QCoreApplication.translate
        Records.setWindowTitle(_translate("Records", "Records"))
        self.label.setText(_translate("Records", "Search"))
        self.label_2.setText(_translate("Records", "Performance"))
        self.label_3.setText(_translate("Records", "Customer"))
        self.label_4.setText(_translate("Records", "Seat ID"))
        self.label_5.setText(_translate("Records", "Customer Type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Records = QtWidgets.QMainWindow()
    ui = Ui_Records()
    ui.setupUi(Records)
    Records.show()
    sys.exit(app.exec_())
