# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeatBooking.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeatBooking(object):
    def setupUi(self, SeatBooking):
        SeatBooking.setObjectName("SeatBooking")
        SeatBooking.resize(922, 642)
        self.centralwidget = QtWidgets.QWidget(SeatBooking)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Bookingframe = QtWidgets.QFrame(self.centralwidget)
        self.Bookingframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Bookingframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bookingframe.setObjectName("Bookingframe")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Bookingframe)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 60, 771, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.SeatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.SeatLayout.setContentsMargins(0, 0, 0, 0)
        self.SeatLayout.setObjectName("SeatLayout")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Bookingframe)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 90, 227))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.BookingLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.BookingLayout.setContentsMargins(0, 0, 0, 0)
        self.BookingLayout.setObjectName("BookingLayout")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.BookingLayout.addWidget(self.label_12)
        self.Performance_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Performance_comboBox.setObjectName("Performance_comboBox")
        self.BookingLayout.addWidget(self.Performance_comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.BookingLayout.addItem(spacerItem)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.BookingLayout.addWidget(self.label_13)
        self.Cust_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Cust_comboBox.setObjectName("Cust_comboBox")
        self.BookingLayout.addWidget(self.Cust_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.BookingLayout.addItem(spacerItem1)
        self.Book_PushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Book_PushButton.setObjectName("Book_PushButton")
        self.BookingLayout.addWidget(self.Book_PushButton)
        self.Front_Label = QtWidgets.QLabel(self.Bookingframe)
        self.Front_Label.setGeometry(QtCore.QRect(120, 10, 771, 43))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Front_Label.setFont(font)
        self.Front_Label.setAutoFillBackground(False)
        self.Front_Label.setFrameShape(QtWidgets.QFrame.Panel)
        self.Front_Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Front_Label.setScaledContents(False)
        self.Front_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Front_Label.setObjectName("Front_Label")
        self.gridLayout.addWidget(self.Bookingframe, 0, 0, 1, 1)
        SeatBooking.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SeatBooking)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 22))
        self.menubar.setObjectName("menubar")
        SeatBooking.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SeatBooking)
        self.statusbar.setObjectName("statusbar")
        SeatBooking.setStatusBar(self.statusbar)

        self.retranslateUi(SeatBooking)
        QtCore.QMetaObject.connectSlotsByName(SeatBooking)

    def retranslateUi(self, SeatBooking):
        _translate = QtCore.QCoreApplication.translate
        SeatBooking.setWindowTitle(_translate("SeatBooking", "Seat Booking"))
        self.label_12.setText(_translate("SeatBooking", "Performance"))
        self.label_13.setText(_translate("SeatBooking", "Customer"))
        self.Book_PushButton.setText(_translate("SeatBooking", "Book"))
        self.Front_Label.setText(_translate("SeatBooking", "Front"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SeatBooking = QtWidgets.QMainWindow()
    ui = Ui_SeatBooking()
    ui.setupUi(SeatBooking)
    SeatBooking.show()
    sys.exit(app.exec_())
