# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\Computer Science\Transfer Project\UI\SeatInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeatInfo(object):
    def setupUi(self, SeatInfoMenu):
        SeatInfoMenu.setObjectName("SeatInfoMenu")
        SeatInfoMenu.resize(185, 163)
        self.centralwidget = QtWidgets.QWidget(SeatInfoMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 108))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        SeatInfoMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SeatInfoMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 185, 21))
        self.menubar.setObjectName("menubar")
        SeatInfoMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SeatInfoMenu)
        self.statusbar.setObjectName("statusbar")
        SeatInfoMenu.setStatusBar(self.statusbar)

        self.retranslateUi(SeatInfoMenu)
        QtCore.QMetaObject.connectSlotsByName(SeatInfoMenu)

    def retranslateUi(self, SeatInfoMenu):
        _translate = QtCore.QCoreApplication.translate
        SeatInfoMenu.setWindowTitle(_translate("SeatInfoMenu", "SeatInfoMenu"))
        self.label_4.setText(_translate("SeatInfoMenu", "Customer:"))
        self.label_2.setText(_translate("SeatInfoMenu", "Phone No:"))
        self.label.setText(_translate("SeatInfoMenu", "Cust Type:"))
        self.label_3.setText(_translate("SeatInfoMenu", "Seat ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SeatInfoMenu = QtWidgets.QMainWindow()
    ui = Ui_SeatInfo()
    ui.setupUi(SeatInfoMenu)
    SeatInfoMenu.show()
    sys.exit(app.exec_())
