# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeatInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeatInfo(object):
    def setupUi(self, SeatInfo):
        SeatInfo.setObjectName("SeatInfo")
        SeatInfo.resize(230, 189)
        self.centralwidget = QtWidgets.QWidget(SeatInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 128))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.customer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.customer.setReadOnly(True)
        self.customer.setObjectName("customer")
        self.horizontalLayout_4.addWidget(self.customer)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.phoneNumber = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.phoneNumber.setReadOnly(True)
        self.phoneNumber.setObjectName("phoneNumber")
        self.horizontalLayout_2.addWidget(self.phoneNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.customerType = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.customerType.setReadOnly(True)
        self.customerType.setObjectName("customerType")
        self.horizontalLayout.addWidget(self.customerType)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.seatId = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.seatId.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.seatId.setReadOnly(True)
        self.seatId.setObjectName("seatId")
        self.horizontalLayout_3.addWidget(self.seatId)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        SeatInfo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SeatInfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 230, 22))
        self.menubar.setObjectName("menubar")
        SeatInfo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SeatInfo)
        self.statusbar.setObjectName("statusbar")
        SeatInfo.setStatusBar(self.statusbar)

        self.retranslateUi(SeatInfo)
        QtCore.QMetaObject.connectSlotsByName(SeatInfo)

    def retranslateUi(self, SeatInfo):
        _translate = QtCore.QCoreApplication.translate
        SeatInfo.setWindowTitle(_translate("SeatInfo", "Seat Information"))
        self.label_4.setText(_translate("SeatInfo", "Customer:"))
        self.label_2.setText(_translate("SeatInfo", "Phone No:"))
        self.label.setText(_translate("SeatInfo", "Cust Type:"))
        self.label_3.setText(_translate("SeatInfo", "Seat ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SeatInfo = QtWidgets.QMainWindow()
    ui = Ui_SeatInfo()
    ui.setupUi(SeatInfo)
    SeatInfo.show()
    sys.exit(app.exec_())
